name: aabird
description: "A new Flutter project to test features using Wagtail"
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.8.1
  audioplayers: ^5.2.1
  http: ^1.1.0
  google_fonts: ^6.3.2
  auto_size_text: ^3.0.0
  animate_gradient: ^0.0.3
  speech_to_text: ^7.3.0
  flutter_tts: ^3.8.5
  sqflite: ^2.3.0          # For local storage
  path: ^1.8.3             # Required for SQLite
  permission_handler: ^11.0.1  # For microphone permissions


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  image_path: "assets/images/wagtail_icon.png"
  android: true

  web:
    generate: true
    image_path: "assets/images/wagtail_icon.png"

  windows:
    generate: true
    image_path: "assets/images/wagtail_icon.png"


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/
    - assets/videos/
